# Site settings
title: "sperlingXX's resume"
description: "sperlingXX's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Xu Xiao"
resume_title:                   "Software Engineer: ML infra."

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lovedreamf@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "lovedreamf@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a software engineer interested in machine learning infrastructure and distributed computing. Currently, I work for Ant Financial as a machine learning platform engineer. I am familiar with Kubeflow, XGBoost and Apache Spark.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_contribution:    true
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sperlingxx"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
